### ISSUE TITLE
Install yamlfmt, if its not available

### ISSUE THREAD

**Issue by bluebrown** [bluebrown/vscode-extension-yamlfmt#2]
It could be more user-friendly to install yamlfmt for the user, if it's not already installed on the system

**Comment by Araxeus** [comment]
I wanted this extension to format my `github-actions-workflow` files, but not having Go installed I had to find another way to install yamlfmt

so I used https://github.com/Araxeus/vendorfiles (installed using bun/nodejs) to install and keep it updated from github releases
<details>
  <summary>with the following config:</summary>
  
```yaml
  yamlfmt:
    version: v0.12.1
    repository: https://github.com/google/yamlfmt
    vendorFolder: "{vendorFolder}"
    files:
      - "{release}/yamlfmt_{version}_Windows_x86_64.tar.gz":
          - yamlfmt.exe
``` 
</details>

> I write this hoping it can help someone in my situation
